services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    # networks:
    #   - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healths"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s